### ISSUE TITLE
parallel_chimera_preprocess_pdbbind_2018_refined_docking.sh

### ISSUE THREAD

**Issue by guzh970630** [LLNL/FAST#3]
This "parallel_chimera_preprocess_pdbbind_2018_refined_docking.sh" runs incorrectly, num_jobs is missing parameters, and "parallel -j0 --timeout 600 --delay 2.5 --joblog prepare_chimera_pdbbind_2018_refined_docking_${timestamp}.out.test_pipeline: find_complex_run_test./prepare_complex_parse./ /**/*_pocket.pdb" file not found

**Comment by wderekjones** [comment]
the script is mostly provided as a template for what you could use in your own environment. you may need to change the paths to match the structure reflected on your system. I think your issue lies in the `find docking_parse_pipeline_test_run/**/*_pocket.pdb` which would need to be adapted to find (no pun intended) the pocket.pdb files in your system. If it still isn't working, let us know and we can try to improve the documentation.
