### ISSUE TITLE
Why `partialchrage` of pocket or ligand should not be ALL 0?

### ISSUE THREAD

**Issue by xuelianl** [LLNL/FAST#8]
Hi,
I want to know why we require the `partialchrage` of **at least one atom of pocket or ligand not be 0** when we extract data? Your prompt reply would be greatly appreciated!
https://github.com/LLNL/FAST/blob/5b8c2d775a67ad1716e26938492f1f5d037962a3/data_util/extract_pafnucy_data_with_docking.py#L94-L100

**Comment by wderekjones** [comment]
Hi @xuelianl,

this code was heavily adapted from the Pafnucy paper. The purpose of this condition is to serve as a quality control. The comment was probably from me during my first pass-through and it seems to have still made it there...what that is saying is if there is ANY atom with a 0 partial charge, that there has likely been an error at some point in the data preparation. The comment in this case states ALL rather than ANY...it should be ANY. Hopefully that's clear. 

- here's the link to their gitlab: https://gitlab.com/cheminfIBB/pafnucy 
- here's the link to their paper: https://academic.oup.com/bioinformatics/article/34/21/3666/4994792

**Comment by xuelianl** [comment]
Thanks for your patient answer!
